### ISSUE TITLE
Program refuses to run

### ISSUE THREAD

**Issue by Gaalidas** [AstroTechies/AstroModLoader#11]
Upon first running, you have to tell windows it's allowed.  After doing so it runs for half a second and quits.  No errors, no on-screen dialogues... just nothing.

**Comment by Gaalidas** [comment]
Apparently, if the Mods and/or Paks directories exist, from a prior version, in the local saved directory, the program will refuse to run.  Upon deleting both of these files, the program begins to function properly.

Also, running the game with any mods activated causes the game to shut itself down.

**Comment by konsti219** [comment]
The mods you are using are simply outdated
