### ISSUE TITLE
Cannot run mod loader.

### ISSUE THREAD

**Issue by OutragedMetro** [AstroTechies/AstroModLoader#12]
I downloaded the Astro Mod Loader on first launch it ran fine. Allowed me to drag and drop my mod which it installed. But now the Mod loader wont run. When I look at task Manager it tries to open the program then fails to run.

**Comment by konsti219** [comment]
What mod did you try to install? 95% of mods got broken with the snails update. The modding discord has a list of working mods.

Anyways won't fix.
