### ISSUE TITLE
Issue with 1.6.1

### ISSUE THREAD

**Issue by ConradRHamilton** [AstroTechies/AstroModLoader#15]
When the snail update broke AstroModLoader, I deleted all of it from my machine and decided I'd re-download it when/if it got fixed. 

Downloaded the updated version, but I can't drag&drop the mods into the loader. Did I mess something up with the install?

**Comment by konsti219** [comment]
This is unlikely a problem with the actual modloader. Please come to the astroneer modding discord get help you resolve this.
