### ISSUE TITLE
super condenser mod works fine for me on windows 10, but for my friend on windows 11 its considered malformed

### ISSUE THREAD

**Issue by AltoidDev** [AstroTechies/AstroModLoader#16]
we've tried redownloading both the mod and loader, but nothing changed, we also tried manual install, but no luck

**Comment by konsti219** [comment]
We are no longer actively maintaining this version of the Modloader. Therefore we can't guarantee support on Windows 11.

But are you sure that you both downloaded the same file from the same place? The one here is most likely to work https://astroneermods.space/m/Supercondenser

If you are playing on the Microsoft store version it might also be causing if win 11 changed something about how store apps store data.
