### ISSUE TITLE
Somethin

### ISSUE THREAD

**Issue by COMRADEKLLR** [AstroTechies/AstroModLoader#17]
Um Hey I dont Know if its me or the loader but every time i try load to these mods The Alternate Start mod, Minimap, character Customization freedom lite, generous air, generous power, generous storage, generous tethers, and tuned crafting All In One the game will get like 2 seconds in and then fail but for some reason these mods dont make the game fail Super Condenser, mo'tradables, Better Power, 
and the adapter mod and it gets frustrating because i downloaded these cool mod and now i cant play i didnt mean offence against you and your team

**Comment by COMRADEKLLR** [comment]
oh and my build id is 9017571 and i play on steam

**Comment by konsti219** [comment]
All of those mods are broken
