### ISSUE TITLE
VIRUS FOUND

### ISSUE THREAD

**Issue by f8lerror** [AstroTechies/AstroModLoader#5]
![virus report](https://user-images.githubusercontent.com/6183402/115118452-0d0fa680-9f58-11eb-8e7f-a32515f3a26e.png)
Your program has a virus on it my system caught it at 0211 this morning and quarantined it. I double checked by downloading it again to a different system and it is still infect.

**Comment by Xavius-Night** [comment]
Same thing just happened to me when I tried to run it today at 1244

**Comment by IOnlyFetchBranches** [comment]
Same thing here, is this safe

**Comment by IOnlyFetchBranches** [comment]
It was working fine yesterday...

**Comment by Xavius-Night** [comment]
It was working for me the last couple of days, then I tried starting it today and it gave the error; this either means that the program (which was listed as a Trojan) had a specified start timer on it that it was waiting for, or that an update to _something_ caused it to get registered as a trojan.
Now, something to bring up in that facet, I did update my computer last night when I turned it off - there is the chance that's connected, either by updating security software that caught the virus or by updating the system mistook it for a virus, but I don't have clear answers which it is, at present.

**Comment by IOnlyFetchBranches** [comment]
I think its fine guys, its a mod loader. checked the commit history i don't see anything malicious has changed... also virus total only has 4 hits and all looks like generic false positive readings.. but nevertheless... iw ill be waiting for the response from the repo owner to confirm...

**Comment by Xavius-Night** [comment]
I cannot even download it at this point because windows instantly stops the download and deletes it. What is causing this?

**Comment by fallenpro** [comment]
If this is being detected as a virus, it's a false positive. Had the exact same problem with Norton (detected it as ws.reputation.1 aka a program with low or no reputation) and had to go whitelist it. I can say from experience so far that it's not a virus.

**Comment by konsti219** [comment]
Works for me. Just disable App & Browser control under security. 
@atenfyr Should we close?

**Comment by f8lerror** [comment]
Well it isn't downloadable because windows kills it the second you try. I would find out why it's calling it a false positive and fix that so it doesn't show up like that anymore. Until that happens it's going to be difficult to convince people that it's not a virus and it's safe. I loved the app and it worked perfectly until it didn't, and I'm not the only one having the issue meaning it's not just me. My system did do a windows update a couple of days ago but it worked fine until yesterday morning.

**Comment by atenfyr** [comment]
Hi all,

AstroModLoader binaries from the Releases tab of this repository do not contain any sort of malware. "Trojan:Win32/Emali.A!cl" is a common Windows Defender false-positive for certain applications, with little to no discernible cause. I will take the necessary steps to submit the latest version (v1.5.1.0) as a false positive to Microsoft for analysis; in the meantime, if you do not trust the executable provided, you are free to inspect the source code in this repository and compile AstroModLoader with it yourself.

adolescent
