### ISSUE TITLE
Does it work on ubuntu

### ISSUE THREAD

**Issue by ghost** [AstroTechies/AstroModLoader#6]
Does it work on ubuntu

**Comment by konsti219** [comment]
The astroneer server software is fundamentally incompatible with Linux and wine doesn't work.

(Next time ask in the astroneer discord instead of making an issue)

**Comment by atenfyr** [comment]
@konsti219 What does AstroModLoader have to do with server software, and how is the developer-endorsed Astroneer Discord server a good place to ask this kind of question when modding is against the EULA in the first place?

**Comment by atenfyr** [comment]
AstroModLoader uses WinForms which isn't intended for usage on Linux, but there is an "unofficial" Linux build on the Astroneer modding Discord server that I can't vouch for
