### ISSUE TITLE
Error with new version of Astroneer

### ISSUE THREAD

**Issue by TheGrey01** [AstroTechies/AstroModLoader#8]
There was a recent update to astroneer and the mod loader now errors when you try to click the play button.

**Comment by AlisterGontineac** [comment]
Doesn't even launch for me

**Comment by TheGrey01** [comment]
My guess is you don't have the proper version of .Net installed then.

**Comment by elijahhale** [comment]
Can you explain what you mean? I am also having the no-launch issue

**Comment by TheGrey01** [comment]
I assume you both mean the mod loader itself and not Astroneer while using the mod loader (because that's the issue I am referring to).  If you mean astroneer and while clicking the play button from within the mod loader THAT is the issue I have.  My reply to Alister was if the Modloader itself isn't even running (ie won't start or gives an error when attempting to start) then it's probably due to the wrong version of .Net (you always want to make sure you have the most recent version (or at least one that was released roughly around the same time as the program in question) which would be verions somewhere around 4.5.  If you do a lot of moding like I used to you'll probably already have it installed which means the issue you are having is something completely different.

**Comment by bWildcard** [comment]
I cant even load the game normally with the mods installed

the Mod Loader wont even Load

how do i unload the mods if I cannot open the launcher?

I was able to get the game to launch by hunting down the Mods and Paks removed both into a backup folder
C:\Users\PC\AppData\Local\Astro\Saved

**Comment by TheGrey01** [comment]
I can start the Mod loader, which works fine for me, but my game will start up for like a split second and crash, however this is apparently a known issue over on the discord and I'm not sure what they are going to do about it.  Hopefully it'll get fixed so we can go back to using mods.

**Comment by konsti219** [comment]
This update broke a lot of mods and the mod loader partially.

**Don't expect a full fix soon**
